import json
from pathlib import Path
from playwright.sync_api import sync_playwright, expect

root = Path(__file__).resolve().parents[1]
access = json.loads((root / 'test-results/ui-access.json').read_text())
with sync_playwright() as p:
    browser = p.chromium.launch(headless=True, channel='msedge')
    context = browser.new_context(viewport={'width': 1440, 'height': 1000})
    page = context.new_page()
    errors = []
    page.on('pageerror', lambda error: errors.append(str(error)))
    page.goto(access['url'])
    page.wait_for_load_state('networkidle')
    expect(page.locator('#owner')).to_be_visible()
    expect(page.locator('html')).to_have_attribute('data-theme', 'dark')
    rendered_text = page.locator('body').inner_text()
    for decorative_glyph in ['▤', '↗', '▱', '◷', '⚙', '＋', '↥', '▰', '⌄', '△', '✓']:
        assert decorative_glyph not in rendered_text, f'Found decorative glyph: {decorative_glyph}'
    page.screenshot(path=str(root / 'test-results/dashboard-desktop.png'), full_page=True)
    assert page.locator('body').evaluate('(e) => e.scrollWidth <= window.innerWidth')
    expect(page.get_by_role('heading', name='Your inbox.')).to_be_visible()
    page.get_by_role('button', name='Enable receiving', exact=True).click()
    expect(page.locator('#receiver-title')).to_have_text('Ready to receive')
    expect(page.locator('#receive-duration')).to_be_enabled()
    page.locator('#receive-duration').select_option('240')
    expect(page.locator('#toast')).to_have_text('Receiving time updated.')
    expect(page.locator('#receive-duration')).to_have_value('240')
    assert page.evaluate("fetch('/api/state').then(r=>r.json()).then(s=>s.receivingWindowMinutes)") == 240
    pending = page.evaluate("""async () => {
      const r=await fetch('/api/uploads',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({path:'progress-check.mp4',size:1024*1024*1024,batch:crypto.randomUUID(),batchFiles:3,batchBytes:1024*1024*1024,destination:'local'})});return r.json();
    }""")
    expect(page.locator('#incoming-panel')).to_be_visible(timeout=10000)
    expect(page.locator('#incoming-list')).to_contain_text('1.0 GB')
    expect(page.locator('#incoming-list')).to_contain_text('progress-check.mp4')
    expect(page.locator('#incoming-list')).to_contain_text('0 received · 3 remaining')
    expect(page.locator('#incoming-list progress')).to_have_count(1)
    page.evaluate("""async id => {
      const r=await fetch(`/api/uploads/${id}`,{method:'PUT',headers:{'Upload-Offset':'0'},body:new Uint8Array(4*1024*1024)});
      if(!r.ok)throw new Error(await r.text());
    }""", pending['id'])
    expect(page.locator('.transfer-meta')).to_contain_text('remaining', timeout=10000)
    page.screenshot(path=str(root / 'test-results/incoming-overall.png'), full_page=True)
    page.get_by_role('button', name='Cancel current file').click()
    expect(page.locator('#incoming-panel')).to_be_hidden(timeout=10000)
    page.locator('#files').set_input_files({'name': 'owner-smoke.txt', 'mimeType': 'text/plain', 'buffer': b'Owner browser upload verified.'})
    expect(page.locator('#queue')).to_contain_text('Received and size verified', timeout=15000)
    owner_group = page.locator('.file-group').filter(has_text='owner-smoke.txt')
    expect(owner_group.locator('summary')).to_contain_text('My uploads')
    expect(owner_group.locator('.file-row')).to_be_hidden()
    owner_group.locator('summary').click()
    page.locator('.open-saved').first.click()
    expect(page.locator('#toast')).to_contain_text('Saved at')
    expect(page.get_by_role('link', name='Download a copy').first).to_be_visible()
    existing_count = page.locator('#file-count').inner_text()
    page.locator('#files').set_input_files({'name': 'owner-smoke.txt', 'mimeType': 'text/plain', 'buffer': b'Owner browser upload verified.'})
    expect(page.locator('#toast')).to_have_text(__import__('re').compile(r'(already received|matched a saved file)'), timeout=15000)
    expect(page.locator('#queue')).to_be_hidden()
    expect(page.locator('#file-count')).to_have_text(existing_count)
    page.locator('#files').set_input_files([
        {'name': 'alpha.jpg', 'mimeType': 'image/jpeg', 'buffer': b'alpha'},
        {'name': 'beta.jpg', 'mimeType': 'image/jpeg', 'buffer': b'beta'},
    ])
    expect(page.locator('#queue')).to_contain_text('2 received · 0 remaining', timeout=15000)
    grouped = page.locator('.file-group').filter(has_text='alpha.jpg')
    expect(grouped).to_have_count(1)
    expect(grouped.locator('.file-row').first).to_be_hidden()
    grouped.locator('summary').click()
    expect(grouped.locator('.file-row')).to_have_count(2)
    page.wait_for_timeout(1800)
    expect(grouped.locator('.file-row')).to_have_count(2)
    grouped.get_by_role('button', name=__import__('re').compile(r'^Clear ')).click()
    expect(page.locator('#delete-dialog')).to_be_visible()
    expect(page.locator('#delete-title')).to_have_text('Clear upload group')
    page.get_by_role('button', name=__import__('re').compile(r'^Clear group only')).click()
    expect(grouped).to_have_count(0)
    page.locator('#new-request-top').click()
    page.locator('#request-label').fill('Weekend collection')
    page.get_by_role('button', name='Create link', exact=False).click()
    expect(page.locator('#created-link')).to_be_visible()
    guest_url = page.locator('#share-url').input_value()
    page.keyboard.press('Escape')
    page.locator('[data-page="requests"]').click()
    saved_link = page.get_by_label('Upload link for Weekend collection')
    expect(saved_link).to_be_visible()
    expect(saved_link).to_have_value(guest_url)
    page.reload()
    page.wait_for_load_state('networkidle')
    page.locator('[data-page="requests"]').click()
    expect(page.get_by_label('Upload link for Weekend collection')).to_have_value(guest_url)
    guest_context = browser.new_context(viewport={'width': 390, 'height': 844})
    guest = guest_context.new_page()
    guest.on('pageerror', lambda error: errors.append(str(error)))
    guest.goto(guest_url)
    guest.wait_for_load_state('networkidle')
    guest.locator('#guest-name').fill('UI test sender')
    guest.get_by_role('button', name='Request upload access').click()
    expect(guest.locator('#pair-code')).to_have_text(__import__('re').compile(r'[A-F0-9]{6}'))
    page.locator('[data-page="requests"]').click()
    approval = page.locator('.list-row').filter(has_text='UI test sender').first
    expect(approval).to_be_visible(timeout=10000)
    approval.get_by_role('button', name='Approve', exact=True).click()
    expect(guest.locator('#guest-upload')).to_be_visible(timeout=10000)
    guest.locator('#files').set_input_files({'name': 'guest-smoke.txt', 'mimeType': 'text/plain', 'buffer': b'Approved guest browser upload verified.'})
    expect(guest.locator('#guest-queue')).to_contain_text('Received and size verified', timeout=15000)
    guest.screenshot(path=str(root / 'test-results/guest-mobile.png'), full_page=True)
    assert guest.locator('body').evaluate('(e) => e.scrollWidth <= window.innerWidth')
    page.locator('[data-page="activity"]').click()
    expect(page.get_by_role('button', name='Clear activity')).to_be_visible()
    page.once('dialog', lambda dialog: dialog.accept())
    page.get_by_role('button', name='Clear activity').click()
    expect(page.locator('#activity-list')).to_have_text('Your activity will appear here.')
    expect(page.get_by_role('button', name='Clear activity')).to_be_hidden()
    page.locator('[data-page="settings"]').click()
    expect(page.get_by_role('heading', name='Inbox folder', exact=True)).to_be_visible()
    page.locator('#appearance').select_option('light')
    expect(page.locator('html')).to_have_attribute('data-theme', 'light')
    page.reload()
    expect(page.locator('html')).to_have_attribute('data-theme', 'light')
    page.locator('[data-page="settings"]').click()
    page.emulate_media(color_scheme='dark')
    page.locator('#appearance').select_option('system')
    expect(page.locator('html')).to_have_attribute('data-theme', 'dark')
    page.emulate_media(color_scheme='light')
    expect(page.locator('html')).to_have_attribute('data-theme', 'light')
    page.locator('#appearance').select_option('dark')
    page.locator('[data-page="inbox"]').click()
    page.set_viewport_size({'width': 390, 'height': 844})
    page.screenshot(path=str(root / 'test-results/dashboard-mobile.png'), full_page=True)
    assert page.locator('body').evaluate('(e) => e.scrollWidth <= window.innerWidth')
    page.get_by_role('button', name='Pause receiving', exact=True).click()
    expect(page.locator('#receiver-title')).to_have_text('Receiving is paused')
    owner_group = page.locator('.file-group').filter(has_text='owner-smoke.txt')
    if not owner_group.get_attribute('open'):
        owner_group.locator('summary').click()
    owner_group.get_by_role('button', name='Delete owner-smoke.txt', exact=True).click()
    expect(page.locator('#delete-dialog')).to_be_visible()
    page.get_by_role('button', name='Remove record only').click()
    expect(page.locator('.file-row').filter(has_text='owner-smoke.txt')).to_have_count(0)
    page.locator('[data-page="requests"]').click()
    page.once('dialog', lambda dialog: dialog.accept())
    page.locator('#guest-list .list-row').filter(has_text='UI test sender').get_by_role('button', name='Delete record').click()
    expect(page.locator('#guest-list')).not_to_contain_text('UI test sender')
    page.once('dialog', lambda dialog: dialog.accept())
    page.locator('#invite-list .list-row').filter(has_text='Weekend collection').get_by_role('button', name='Delete record').click()
    expect(page.locator('#invite-list')).not_to_contain_text('Weekend collection')
    assert errors == [], errors
    browser.close()
print('Browser checks passed: dark default, saved theme, system theme changes, owner upload, guest request/approval/upload, controls, responsive layout, no JavaScript errors.')
